#!/usr/bin/env python3
"""Two-stage native MikroTik Back to Home client provisioning for Debian 13.

Requires Python 3 and wireguard-tools. Does not start a tunnel or contact a router.
All generated files containing credentials are mode 0600.
"""
import argparse
import base64
import ipaddress
import json
import os
from pathlib import Path
import re
import shutil
import subprocess
import sqlite3
import tempfile
from datetime import datetime, timezone
import sys


class SetupError(Exception):
    pass


def key(value):
    try:
        if len(base64.b64decode(value, validate=True)) != 32:
            raise ValueError()
    except (ValueError, TypeError):
        raise SetupError("Invalid WireGuard key; obtain a complete, untruncated BTH profile.")
    return value


def wg(command, value=None):
    result = subprocess.run(["wg", command], input=value, text=True,
                            capture_output=True, check=False)
    if result.returncode:
        raise SetupError("WireGuard key operation failed; check wireguard-tools installation.")
    return key(result.stdout.strip())


def write_new(path, content):
    """Create without following symlinks or overwriting an existing file."""
    fd = os.open(path, os.O_WRONLY | os.O_CREAT | os.O_EXCL | os.O_NOFOLLOW, 0o600)
    with os.fdopen(fd, "w") as handle:
        handle.write(content)


def endpoint(value):
    # Only configuration data, never shell commands or wg-quick hooks.
    match = re.fullmatch(r"(?:[A-Za-z0-9_.-]+|\[[A-Fa-f0-9:]+\]):([0-9]{1,5})", value)
    if not match or not 1 <= int(match.group(1)) <= 65535:
        raise SetupError("Invalid or truncated peer Endpoint in BTH profile.")
    return value


def parse_profile(text):
    sections = []
    current = None
    allowed = {
        "Interface": {"PrivateKey", "Address", "DNS", "MTU", "ListenPort"},
        "Peer": {"PublicKey", "PresharedKey", "AllowedIPs", "Endpoint", "PersistentKeepalive"},
    }
    for raw in text.splitlines():
        line = raw.split("#", 1)[0].strip()
        if not line:
            continue
        if line in ("[Interface]", "[Peer]"):
            current = (line[1:-1], {})
            sections.append(current)
            continue
        if current is None or "=" not in line:
            raise SetupError("Paste only the plain WireGuard profile, starting with [Interface].")
        name, value = (part.strip() for part in line.split("=", 1))
        kind, fields = current
        if name not in allowed[kind]:
            raise SetupError("Unexpected profile field; shell hooks and routing commands are not accepted.")
        if name in fields:
            raise SetupError("Duplicate field in BTH profile.")
        fields[name] = value
    if not sections or sections[0][0] != "Interface":
        raise SetupError("Profile must start with [Interface].")
    if sum(kind == "Interface" for kind, _ in sections) != 1:
        raise SetupError("Profile must have one Interface section.")
    if len(sections) != 3 or any(kind != "Peer" for kind, _ in sections[1:]):
        raise SetupError("Expected the complete BTH profile with two peers, including its relay peer.")
    return sections[0][1], [fields for _, fields in sections[1:]]


def finish_config(state, raw):
    interface, peers = parse_profile(raw)
    if key(interface.get("PrivateKey", "")) != state["private_key"]:
        raise SetupError("This profile has a different client key. Export the user created by 01-mikrotik-bth.rsc.")
    addresses = [ipaddress.ip_interface(x.strip()) for x in interface.get("Address", "").split(",")]
    if ipaddress.ip_address(state["client_ip"]) not in [x.ip for x in addresses]:
        raise SetupError("BTH profile client address differs from the generated whitelist.")
    mains = 0
    auxiliaries = 0
    seen_keys = set()
    output = ["# Generated by bth_setup.py; management-only routing.",
              "[Interface]", "PrivateKey = " + state["private_key"],
              "Address = " + state["client_ip"] + "/32", "MTU = 1420", ""]
    for peer in peers:
        public = key(peer.get("PublicKey", ""))
        if public in seen_keys:
            raise SetupError("Duplicate peer public key.")
        seen_keys.add(public)
        nets = [ipaddress.ip_network(x.strip(), strict=False)
                for x in peer.get("AllowedIPs", "").split(",")]
        if ipaddress.ip_network("0.0.0.0/0") in nets or ipaddress.ip_network(state["router_ip"] + "/32") in nets:
            mains += 1
            routed = state["router_ip"] + "/32"
        elif nets == [ipaddress.ip_network("0.0.0.0/32")]:
            auxiliaries += 1
            routed = "0.0.0.0/32"
        else:
            raise SetupError("Unrecognized BTH peer routing; keep the generated profile for review.")
        keepalive = peer.get("PersistentKeepalive", "15")
        if not keepalive.isdigit() or not 1 <= int(keepalive) <= 65535:
            raise SetupError("Invalid keepalive; expected a positive BTH keepalive interval.")
        output += ["[Peer]", "PublicKey = " + public]
        if "PresharedKey" in peer:
            output += ["PresharedKey = " + key(peer["PresharedKey"])]
        output += ["AllowedIPs = " + routed, "Endpoint = " + endpoint(peer.get("Endpoint", "")),
                   "PersistentKeepalive = " + keepalive, ""]
    if mains != 1 or auxiliaries != 1:
        raise SetupError("Expected one router peer and one BTH auxiliary peer.")
    return "\n".join(output)


def templates(s):
    name, user = s["name"], s["user"]
    client, router = s["client_ip"], s["router_ip"]
    chain, acl, loop = "BTH-" + name + "-IN", "BTH-" + name + "-ADMIN", "LO-BTH-" + name
    tag = "BTHSETUP:" + name
    provisioning = f'''# PRIVATE: contains this Debian client's private key for native BTH registration.
# RouterOS 7.23.x on CCR2216. Apply locally, once. No existing peers are reset.
# Hostname: {s['label']}
# Description: {s.get('description', '')}
# Client public key: {s['public_key']}
:if ([:len [/ip cloud back-to-home-user find where name="{user}"]] > 0) do={{ :error "BTH user exists; inspect instead of replacing it" }}
# Refuse any existing WireGuard allowed range containing the selected client IP.
:foreach p in=[/interface wireguard peers find] do={{
    :foreach a in=[/interface wireguard peers get $p allowed-address] do={{
        :if ({client} in $a) do={{ :error "VPN client address overlaps an existing peer; choose another --client-ip" }}
    }}
}}
/ip cloud set ddns-enabled=yes
/ip cloud set back-to-home-vpn=enabled
:delay 3s
:if ([:len [/interface wireguard find where name="back-to-home-vpn"]] != 1) do={{ :error "Expected BTH interface not found; inspect IP Cloud" }}
/ip cloud back-to-home-user add name="{user}" client-address={client}/32 private-key="{s['private_key']}" allow-lan=no
/ip cloud force-update
# Export the NEW user's profile privately with:
# /interface wireguard peers show-client-config {user}
# Preserve the two generated peer sections and all key/endpoint values.
'''
    firewall = f'''# Firewall suggestion for {s['label']}; apply locally after 01-mikrotik-bth.rsc.
# Description: {s.get('description', '')}
# Whitelist: {client}/32 on back-to-home-vpn -> {router}/32 TCP 22,8291 and ICMP.
# Other addresses retain their existing policies. No forwarded LAN access is added.
# Review existing dynamic input rules: they must not broadly accept this loopback.
:if ([:len [/interface wireguard find where name="back-to-home-vpn"]] != 1) do={{ :error "BTH interface missing" }}
:if ([:len [/ip firewall filter find where chain="{chain}"]] > 0) do={{ :error "Generated chain exists; do not rerun" }}
:if ([:len [/ip firewall address-list find where list="{acl}"]] > 0) do={{ :error "Generated whitelist exists; inspect before proceeding" }}
:if ([/ip service get winbox port] != 8291 || [/ip service get ssh port] != 22) do={{ :error "Service ports differ; adapt firewall ports first" }}
:if ([/ip service get winbox vrf] != "main" || [/ip service get ssh vrf] != "main") do={{ :error "Management services must be in main VRF for this design" }}
:if ([/ip service get winbox address] != "" || [/ip service get ssh address] != "") do={{ :error "Restricted service bindings: include the VPN client without removing existing permitted sources, then adapt this guard" }}
:if ([:len [/ip firewall filter find where dynamic=no]] = 0) do={{ :error "Expected existing core firewall not found; review before applying" }}
# Reuse an existing exact /32 ONLY if it is on an empty bridge (a loopback).
:local existing [/ip address find where address="{router}/32"]
:if ([:len $existing] > 1) do={{ :error "Duplicate router address" }}
:if ([:len $existing] = 1) do={{
    :local parent [/ip address get $existing interface]
    :if ([:len [/interface bridge find where name=$parent]] != 1) do={{ :error "Router /32 is not on a loopback bridge" }}
    :if ([:len [/interface bridge port find where bridge=$parent]] > 0) do={{ :error "Existing address is on a bridge with ports" }}
}} else={{
    :if ([:len [/interface find where name="{loop}"]] > 0) do={{ :error "Loopback name already exists without the expected address" }}
    :foreach a in=[/ip address find] do={{
        :if ({router} in [/ip address get $a address]) do={{ :error "Router address overlaps a configured subnet; review previous VLAN/DHCP changes" }}
    }}
}}
/ip firewall address-list add list="{acl}" address={client}/32 comment="{tag}:admin"
/ip firewall filter add chain="{chain}" action=drop connection-state=invalid comment="{tag}:invalid"
/ip firewall filter add chain="{chain}" action=accept in-interface=back-to-home-vpn src-address-list="{acl}" protocol=tcp dst-port=22,8291 comment="{tag}:services"
/ip firewall filter add chain="{chain}" action=accept in-interface=back-to-home-vpn src-address-list="{acl}" protocol=icmp comment="{tag}:icmp"
/ip firewall filter add chain="{chain}" action=drop comment="{tag}:deny"
/ip firewall filter add chain=input action=jump jump-target="{chain}" dst-address={router}/32 place-before=[:pick [/ip firewall filter find where dynamic=no] 0] comment="{tag}:jump"
:if ([:len $existing] = 0) do={{
    /interface bridge add name="{loop}" protocol-mode=none arp=disabled comment="{tag}:loopback"
    /ip address add address={router}/32 network={router} interface="{loop}" comment="{tag}:address"
}}
/ip service set winbox disabled=no
/ip service set ssh disabled=no
# No WAN management allow rule, dst-nat, VLAN, DHCP or default-route changes.
# Native BTH supplies its transport rule and relay mechanism.
'''
    rollback = f'''# Apply locally only. Disconnects the new client, preserves pre-existing peers.
# Removes a loopback only when created by this generated configuration.
/ip cloud back-to-home-user remove [find where name="{user}"]
/ip address remove [find where comment="{tag}:address"]
/ip firewall filter remove [find where comment="{tag}:jump"]
/ip firewall filter remove [find where chain="{chain}"]
/ip firewall address-list remove [find where list="{acl}"]
/interface bridge remove [find where comment="{tag}:loopback"]
# DDNS/BTH and service enablement are left enabled to preserve existing access.
'''
    return tuple("{\n" + text + "}\n" for text in (provisioning, firewall, rollback))


def registry(directory):
    path = directory / "bth-registry.sqlite3"
    if not path.exists():
        try:
            write_new(path, "")
        except FileExistsError:
            pass
    if path.is_symlink() or not path.is_file():
        raise SetupError("Refusing a symlink or non-file SQLite registry.")
    os.chmod(path, 0o600)
    db = sqlite3.connect(path, timeout=15, isolation_level=None)
    db.row_factory = sqlite3.Row
    db.execute("PRAGMA journal_mode=DELETE")
    db.execute("""CREATE TABLE IF NOT EXISTS routers (
        name TEXT PRIMARY KEY,
        router_ip TEXT NOT NULL UNIQUE,
        hostname TEXT NOT NULL COLLATE NOCASE UNIQUE,
        description TEXT NOT NULL,
        client_ip TEXT NOT NULL,
        status TEXT NOT NULL CHECK(status IN ('generated','ready')),
        state_json TEXT NOT NULL,
        artifacts_json TEXT NOT NULL,
        client_config TEXT,
        created_at TEXT NOT NULL,
        updated_at TEXT NOT NULL
    )""")
    return db


def prompt(value, title, default):
    if value is not None:
        return value.strip()
    try:
        answer = input(title + (" [" + default + "]" if default else "") + ": ").strip()
    except EOFError:
        raise SetupError("Missing input. Supply --router-ip, --hostname and --description for unattended generation.")
    return answer or default


def private_ip(value):
    try:
        address = ipaddress.IPv4Address(value)
    except ipaddress.AddressValueError:
        raise SetupError("Enter an IPv4 address without a subnet mask.")
    ranges = ("10.0.0.0/8", "172.16.0.0/12", "192.168.0.0/16")
    if not any(address in ipaddress.ip_network(net) for net in ranges):
        raise SetupError("Use an RFC1918 private IPv4 address.")
    return str(address)


def metadata(args, old=None, db=None, exclude=None):
    old = old or dict(router_ip="10.231.1.10", hostname="bongao-catv_core-router", description="")
    router = private_ip(prompt(args.router_ip, "BTH access IP (router loopback)", old["router_ip"]))
    if db is not None:
        unique(db, args.name, router, "", exclude=exclude)
    host = prompt(args.hostname, "Hostname", old["hostname"])
    description = prompt(args.description, "Short description", old["description"])
    if not re.fullmatch(r"[A-Za-z0-9_.-]{1,63}", host):
        raise SetupError("Hostname must contain 1-63 letters, digits, dots, hyphens or underscores.")
    if not description or len(description) > 240 or any(ord(c) < 32 or ord(c) == 127 for c in description):
        raise SetupError("Description must be a single line of 1-240 printable characters.")
    return router, host, description


def unique(db, name, router, host, exclude=None):
    for field, value, label in (("router_ip", router, "BTH IP"), ("hostname", host, "Hostname"), ("name", name, "Profile name")):
        row = db.execute("SELECT name,router_ip,hostname,description FROM routers WHERE " + field + "=?", (value,)).fetchone()
        if row and row["name"] != exclude:
            raise SetupError(
                label + " already registered: " + row["router_ip"] + " | " + row["hostname"] + " | " + row["description"]
                + "\nNo configuration was generated. Edit the existing entry with:"
                + "\n  sudo python3 ./bth_setup.py edit --name " + row["name"]
                + "\nOr rerun init using a different IP, hostname and profile name."
                + "\nIf using --directory, include that same option in the edit command.")


def artifacts(state):
    result = {"state.json": json.dumps(state, indent=2) + "\n",
              "client-interface.pending": "[Interface]\nPrivateKey = " + state["private_key"]
              + "\nAddress = " + state["client_ip"] + "/32\nMTU = 1420\n"}
    result.update(zip(("01-mikrotik-bth.rsc", "02-mikrotik-firewall.rsc", "03-mikrotik-rollback.rsc"), templates(state)))
    return result


def replace_private(path, content):
    fd, name = tempfile.mkstemp(prefix=path.name + ".", dir=path.parent)
    temporary = Path(name)
    try:
        with os.fdopen(fd, "w") as handle:
            handle.write(content)
        os.replace(temporary, path)
    finally:
        if temporary.exists():
            temporary.unlink()


def show(row):
    # Never display state_json, artifacts_json or client_config: they contain keys.
    print(" | ".join(str(row[k]) for k in ("name", "router_ip", "hostname", "description", "status")))


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("action", choices=["init", "finish", "list", "show", "edit"])
    parser.add_argument("--name", default="bongao", help="WireGuard interface name, maximum 12 characters")
    parser.add_argument("--directory", type=Path, default=Path("/etc/wireguard"), help="Configuration and shared registry directory")
    parser.add_argument("--router-ip", help="BTH access IP; prompted by init/edit if omitted")
    parser.add_argument("--client-ip", default="192.168.216.10", help="Unused address in the existing BTH client subnet, init only")
    parser.add_argument("--hostname", "--label", dest="hostname", help="Registry hostname; does not rename the live CCR")
    parser.add_argument("--description", help="Short description; prompted by init/edit if omitted")
    parser.add_argument("--profile", type=Path, help="Plain exported BTH profile, required by finish")
    args = parser.parse_args()
    os.umask(0o077)
    if not re.fullmatch(r"[a-z][a-z0-9-]{0,11}", args.name):
        raise SetupError("Name must start with a lowercase letter and contain 1-12 lowercase letters, digits or hyphens.")
    directory = args.directory.expanduser().absolute()
    if directory == Path("/etc/wireguard") and os.geteuid() != 0:
        raise SetupError("Run with sudo when writing /etc/wireguard.")
    if directory.is_symlink():
        raise SetupError("Refusing a symlink configuration directory.")
    directory.mkdir(mode=0o700, parents=True, exist_ok=True)
    db = registry(directory)
    state_dir = directory / (".bth-" + args.name)
    target = directory / (args.name + ".conf")
    try:
        if args.action == "list":
            print("PROFILE | BTH IP | HOSTNAME | DESCRIPTION | STATUS")
            for row in db.execute("SELECT * FROM routers ORDER BY router_ip"):
                show(row)
            return
        row = db.execute("SELECT * FROM routers WHERE name=?", (args.name,)).fetchone()
        if args.action == "show":
            if row is None:
                raise SetupError("No registered profile with this name.")
            show(row)
            print("Created: " + row["created_at"] + " | Updated: " + row["updated_at"])
            return
        if args.action == "init":
            router, host, description = metadata(args, db=db)
            client = private_ip(args.client_ip)
            if router == client:
                raise SetupError("Router and VPN client addresses must differ.")
            db.execute("BEGIN IMMEDIATE")
            unique(db, args.name, router, host)
            if target.exists() or target.is_symlink():
                raise SetupError("Configuration already exists and will not be overwritten. Choose another --name.")
            if state_dir.exists() or state_dir.is_symlink():
                raise SetupError("Existing state is not registered here; preserve it and use a new --name. Keys will not be replaced.")
            if not shutil.which("wg"):
                raise SetupError("Install dependencies: sudo apt install python3 wireguard-tools")
            private = wg("genkey")
            state = dict(name=args.name, user="debian-" + args.name, router_ip=router,
                         client_ip=client, label=host, description=description,
                         private_key=private, public_key=wg("pubkey", private + "\n"))
            files = artifacts(state)
            now = datetime.now(timezone.utc).isoformat()
            db.execute("INSERT INTO routers (name,router_ip,hostname,description,client_ip,status,state_json,artifacts_json,client_config,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?)",
                       (args.name, router, host, description, client, "generated", json.dumps(state),
                        json.dumps(files), None, now, now))
            state_dir.mkdir(mode=0o700)
            try:
                for filename, content in files.items():
                    write_new(state_dir / filename, content)
                db.commit()
            except Exception:
                shutil.rmtree(state_dir)
                raise
            print("Registered " + host + " at " + router + "; files: " + str(state_dir))
            print("Apply 01-mikrotik-bth.rsc, then review/apply 02-mikrotik-firewall.rsc locally on the CCR.")
            print("Privately export: /interface wireguard peers show-client-config " + state["user"])
            print("Then run finish with --profile pointing to the complete plain exported profile.")
            print("No active .conf or network changes were made. The 01 file and SQLite registry contain private keys.")
            return
        if row is None:
            raise SetupError("Profile is not in this SQLite registry. Use list to check the registry or init with a new --name.")
        if state_dir.is_symlink() or not state_dir.is_dir():
            raise SetupError("State directory missing or unsafe.")
        if args.action == "edit":
            router, host, description = metadata(args, dict(row), db=db, exclude=args.name)
            db.execute("BEGIN IMMEDIATE")
            row = db.execute("SELECT * FROM routers WHERE name=?", (args.name,)).fetchone()
            unique(db, args.name, router, host, exclude=args.name)
            if router == row["client_ip"]:
                raise SetupError("Router and VPN client addresses must differ.")
            if router != row["router_ip"] and (row["status"] == "ready" or target.exists() or target.is_symlink()):
                raise SetupError("BTH IP cannot be changed after finalization. Create a separate migration profile with a new --name and unused IP. Hostname/description edits remain available.")
            state = json.loads(row["state_json"])
            state.update(router_ip=router, label=host, description=description)
            old_files = json.loads(row["artifacts_json"])
            new_files = artifacts(state)
            for filename, content in old_files.items():
                path = state_dir / filename
                if path.is_symlink() or not path.is_file() or path.read_text() != content:
                    raise SetupError("Generated file was changed outside this tool; edit stopped to preserve it: " + filename)
            changed = []
            try:
                for filename, content in new_files.items():
                    replace_private(state_dir / filename, content)
                    changed.append(filename)
                db.execute("UPDATE routers SET router_ip=?,hostname=?,description=?,state_json=?,artifacts_json=?,updated_at=? WHERE name=?",
                           (router, host, description, json.dumps(state), json.dumps(new_files),
                            datetime.now(timezone.utc).isoformat(), args.name))
                db.commit()
            except Exception:
                for filename in changed:
                    replace_private(state_dir / filename, old_files[filename])
                raise
            print("Updated registry and generated files; client keys preserved. No live router or running tunnel was changed.")
            print("If RouterOS files were already applied, do not reimport them blindly; coordinate any IP migration separately.")
            return
        if args.profile is None:
            raise SetupError("finish requires --profile PATH to the new user's generated BTH profile.")
        db.execute("BEGIN IMMEDIATE")
        row = db.execute("SELECT * FROM routers WHERE name=?", (args.name,)).fetchone()
        if row["status"] == "ready" or target.exists() or target.is_symlink():
            raise SetupError("Configuration already finalized or present; it will not be overwritten.")
        state = json.loads(row["state_json"])
        configuration = finish_config(state, args.profile.read_text())
        write_new(target, configuration)
        try:
            db.execute("UPDATE routers SET status='ready',client_config=?,updated_at=? WHERE name=?",
                       (configuration, datetime.now(timezone.utc).isoformat(), args.name))
            db.commit()
        except Exception:
            target.unlink()
            raise
        print("Created " + str(target) + " with permissions 0600; final configuration saved to SQLite.")
        print("Router route: " + state["router_ip"] + "/32; normal Internet and DNS stay unchanged.")
        print("Connect manually: sudo wg-quick up " + str(target))
    finally:
        if db.in_transaction:
            db.rollback()
        db.close()


if __name__ == "__main__":
    try:
        main()
    except (SetupError, OSError, ValueError, KeyError, sqlite3.Error) as exc:
        print("Error: " + str(exc), file=sys.stderr)
        sys.exit(1)

